User.create(name: "Dave")
User.create(name: "Ray")
User.create(name: "Sasha")
Listing.create(title: "Hot Spot", host_id: 1)
Reservation.create(listing_id: 1, guest_id: 3)
Reservation.create(listing_id: 1, guest_id: 2)
Review.create(reservation_id: 1, rating: 4, guest_id: 1)
Review.create(reservation_id: 2, rating: 2, guest_id: 2)
Listing.create(title: "Sasha Spot", host_id: 3)
Reservation.create(listing_id: 2, guest_id: 1)
Review.create(reservation_id: 3, rating: 3, guest_id: 1)
ray = User.find(2)
dave = User.find(1)
sasha = User.find(3)
ray_trip = Reservation.find(2)
sasha_trip = Reservation.find(1)
dave_trip = Reservation.find(3)
